name: 'Install Java'
description: 'Installs a Java version'
inputs:
  java-version:
    description: 'Java version'
    required: true

runs:
  using: "composite"
  steps:

    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '${{ inputs.java-version }}'
