name: Pull Request - CI
concurrency: 
  group: pull-request-ci-${{ github.head_ref }}

on:
  pull_request:
    types: [opened, reopened, synchronize]

  workflow_dispatch:

jobs:
  build-and-test: 
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies

      - name: Lint
        continue-on-error: true
        run: npm run lint

      - name: Test
        continue-on-error: true
        run: npm run test

      - name: Build
        continue-on-error: true
        run: npm run build

      - name: E2e
        continue-on-error: true
        run: npm run e2e
