name: Pull Reques - CI

concurrency:
  group: pull-request-ci-${{ github.head_ref }}

on:
  pull_request:
    types: [opened, synchronize, reopened] 
    
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Install dependencies
        run: npm ci
      
      - name: Lint
        continue-on-error: true
        run: npm run lint
