name: Push deploy
concurrency: 
  group: push-deploy-${{ github.head_ref }}

on:
  push: 
    branches:
      - "main"

  workflow_dispatch:

env: 
  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

jobs:
  build-and-test: 
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Firebase Tools
        uses: ./.github/composite-actions/setup/firebase-tools

      - name: Install dependencies
        uses: ./.github/composite-actions/install-dependencies

      - name: Deploy ui
        run: npm run deploy
